### ISSUE TITLE
star_grid produces ValueError: Illegal value: Unit("mag").

### ISSUE THREAD

**Issue by carmeloarci** [AstarVienna/ScopeSim_Templates#42] opened 2022-12-20 13:25 UTC
Using dev_master of scopesim and scopesim_templates on python 3.9
I was testing the MICADO example
[2_scopesim_SCAO_1.5mas_astrometry.ipynb](https://github.com/AstarVienna/irdb/blob/dev_master/MICADO/docs/example_notebooks/2_scopesim_SCAO_1.5mas_astrometry.ipynb)
and I found that the example fails in using the  scopesim_templates.star_grid
while is not failing using equivalent arrangement of star made using scopesim_templates.stars.
In the pdf a copy of the notebook with all details
[testing scopesim.pdf](https://github.com/AstarVienna/ScopeSim_Templates/files/10268713/testing.scopesim.pdf)

**Comment by teutoburg** [comment] 2023-09-19 19:01
Using the current versions of all packages, I am unable to reproduce this. The code provided in the PDF runs without any errors. I assume this has been fixed somewhere along the way, so I'm closing the issue. If I missed something, and the error is still occurring somehow, please reopen the issue.

**Closed by teutoburg** 2023-09-19 19:01 UTC
